spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate
  liquibase.change-log: classpath:/db/changelog/changelog-master.yaml

trendyol:
  cache:
    url-to-deeplink: url_to_deeplink
    deeplink-to-url: deeplink_to_url